my_project:
          target: dev
          outputs:
            dev:
              type: postgres
              host: ${{ secrets.DB_HOST }}
              user: ${{ secrets.DB_USER }}
              password: ${{ secrets.DB_PASSWORD }}
              port: ${{ secrets.PORT }}
              dbname: ${{ secrets.DB_NAME }}
              schema: ${{ secrets.DB_SCHEMA }}
              threads: 4
              keepalives_idle: 0
              sslmode: require