services:
  dbt:
      container_name: dbt_container
      image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
      volumes:
        - ./dbt/my_project:/user/app
        - ./dbt/.dbt = "/root/.dbt"
      working_dir: /user/app
      environment:
        - DBT_PROFILES_DIR=/root/.dbt"
      env_file:
        - .env
      networks:
        - my-network
      command: debug
  
  streamlit:
    container_name: streamlit_app
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
